Sprint-2-RG: construct user models and pets
Code-the-Dream-School/ffprac-team3-back pull request #11
Opened 2024-03-28 20:52 UTC by rebs1203

This pull request introduces a User Logon model for login and registration, a User Profile model for storing user information, and initiates a Pets model for future pet management, which will include file upload capabilities later on.

2024-03-28 22:55 UTC, Leonardo-Reyes-Munoz commented on src/models/UserLogon.js
Thank for working on the models Rebeca. I think it would be best to combine the UserProfileSchema with the UserLogon Schema. I do not think there is a need to separate these two. What do you think? Do you think there would be a benefit in keeping these separate?

2024-03-28 22:56 UTC, Leonardo-Reyes-Munoz requested changes
Hello Rebeca, thank you for working on these. I made some additional comments on the UserLogon model, let me know your thoughts.

2024-03-29 03:44 UTC, shreeup reviewed
My opinion on petschema entity, feel free to change 

name: String
age: number
species: string
breed: string

adoptiondetails schema
user_id: reference key to userschema
pet_id: reference key to petschema
adoption_date: datetime

2024-03-29 03:44 UTC, shreeup commented on src/models/UserLogon.js
I too agree with LR

2024-04-02 20:00 UTC, Leonardo-Reyes-Munoz approved these changes

2024-04-02 20:06 UTC, merged